#!/bin/sh

if test -e "$HOME"/.config/ublue/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Filtered Flathub Repo Failed"
        exit 1
fi
echo "30"

echo "# Enabling Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Flathub Repo Failed"
        exit 1
fi
echo "60"

echo "# Installing Chrome"
/usr/bin/flatpak install --user --noninteractive flathub com.google.Chrome
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Chrome Failed"
        exit 1
fi
echo "90"

echo "# Adding Chrome Flatpak permissions"
/usr/bin/flatpak override com.google.Chrome --filesystem=~/.local/share/applications
/usr/bin/flatpak override com.google.Chrome --filesystem=~/.local/share/icons
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Chrome Flatpak permissions Failed"
        exit 1
fi
echo "95"

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/ublue/
cp -n /etc/justfile "$HOME"/.justfile
echo "100"

) | 
     
   zenity --progress --title="uBlue Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi
